spring:
  data:
    rest:
      base-path: /api

  datasource:
    url: jdbc:h2:mem:memdb
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
