INSERT INTO CONTACT (ID, NAME, ZIP_CODE, CITY, HOUSE_NUMBER)
VALUES (1, 'Bruce Wayne', '12345', 'Gotham City', '42');

INSERT INTO PRODUCTION_INSTALLATION (ID, NAME, OUTPUT_POWER, CONTACT_ID)
VALUES (1, 'Wayne Enterprise', 999.9, 1);
